// This a test help class for the purposes of dev-cli and readme generation.
// It is used for testing purposes only as the dev-cli generates a readme for itself in tests
// (see readme tests). For more info on help plugins check out @oclif/plugin-help

export default class TestHelp {
  [x: string]: any

  getCommandHelpForReadme(command: any) {
    const flags = Object.keys(command.flags).join(', ')
    return `Test help generated by test plugin for: ${command.id}\nIt has the following flags: ${flags}`
  }
}
