// this an example of a test help plugin, for the purposes of dev-cli and
// readme generation. For testing it only needs to contain a `command` method. It is used
// here for testing purposes only as the dev-cli generates a readme for itself in tests
// (see readme tests). For more info about HelpPlugins check out @oclif/plugin-help

export default class HelpPlugin {
  command(command: any) {
    const flags = Object.keys(command.flags).join(', ')
    return `Test help generated by test plugin for: ${command.id}\nIt has the following flags: ${flags}`
  }
}
